name: Databricks CI Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:  
      - 'src/my_wheel/**'

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
    #   DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
      DATABRICKS_BUNDLE_ROOT: ${{ github.workspace }}/${{ secrets.DAB_PATH }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          clean: true

      - name: Get Databricks CLI Logged-in User
        run: |
            databricks auth whoami

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install wheel setuptools pytest  # Install the necessary build tools

      - name: Run tests
        run: |
                # pip install pytest  # Ensure pytest is installed
                pytest tests/wheel

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh


    #   - name: Validate, deploy, run tests, and destroy bundle on dev
    #     run: |
    #       set -e
    #       databricks bundle validate
    #       databricks bundle deploy -t dev
    #       databricks bundle run integration_test_end_to_end_job

    #       databricks bundle destroy -t dev --auto-approve


      - name: Archive Databricks Asset Bundle
        run: |
          ls -l $DAB_PATH
          zip -r ${{ github.workspace }}/databricks_build.zip .
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DatabricksBuild
          path: databricks_build.zip
