name: Databricks CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_BUNDLE_ROOT: ${{ github.workspace }}/${{ secrets.DAB_PATH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          clean: true

  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'


      - name: Check for changes in src/my_wheel
        id: check_changes
        run: |
          git fetch origin main  # Make sure the latest history is fetched
          if git diff --exit-code --quiet origin/main -- src/my_wheel; then
            echo "No changes in src/my_wheel"
          else
            echo "Changes detected in src/my_wheel"
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools  # Install the necessary build tools


      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Run Version Bump
        run: |
              python bump_version.py  # Run the Python script that bumps the version

      - name: Validate, deploy, run tests, and destroy bundle on dev
        if: steps.check_changes.outputs.change_detected == 'true'
        run: |
              set -e
              databricks bundle validate
              databricks bundle deploy -t dev
              databricks bundle run -t dev wheel-job

      # - name: Move wheel file to wheels folder
      #   run: |
      #         databricks fs cp /Workspace/Users/bbluestone@outlook.com/.bundle/source-A-bundle/dev/artifacts/.internal/my_wheel-0.1.6-py3-none-any.whl /Workspace/Users/bbluestone@outlook.com/wheels/my_wheel-0.1.weee-py3-none-any.whl
          

      # - name: Validate, deploy, run tests, and destroy bundle on dev
      #   run: |
      #     set -e
      #     databricks bundle validate
      #     databricks bundle deploy -t dev
      #     databricks bundle run integration_test_end_to_end_job
      #     databricks bundle destroy -t dev --auto-approve


      - name: Archive Databricks Asset Bundle
        run: |
          ls -l $DAB_PATH
          zip -r ${{ github.workspace }}/databricks_build.zip .

      - name: Print Path of Artifact Before Uploading
        run: |
          echo "Uploading artifact from path: ${{ github.workspace }}/databricks_build.zip"
          echo "run id: ${{ github.event.workflow_run.id }}"
      
      - name: List Files Before Uploading Artifact
        run: |
          ls -l ${{ github.workspace }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DatabricksBuild
          path: databricks_build.zip
